server: 
  port: 8080 
  servlet: 
    context-path: /SpringBootDemoOne 

spring: 
#  profiles: 
#    active: dev # dev是配置文件application-{}.yml的中间名
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://127.0.0.1:3306/schools?characterEncoding=utf8 
    username: root 
    password: root 
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000                          # 等待连接获取的最大超时时间
  # SpringDateJpa 配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  #jpa: 
    #database: MYSQL
    #show-sql: true
    #hibernate: 
      #ddl-auto: update
  #     spring mvc 视图解析器   
  mvc: 
    view: 
      prefix: /
      suffix: .html
  #集中解决各种编码问题
  #banner.charset=UTF-8
  #http: 
    #encoding: 
      #charset: UTF-8
      #enabled: true 
      #force: true
  #messages:
    #encoding: UTF-8
  # 时间格式化 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss 
  # 时区设置
    time-zone: GMT+8 
  ###SpringBoot文件上传默认配置
  multipart: 
    #默认支持文件上传
    enabled: true
    #文件大小阈值
    file-size-threshold: 0
    # 最大支持文件大小
    max-file-size: 200MB
    # 最大支持请求大小
    max-request-size: 200MB
    
# mybatis读取mapper文件路径    
mybatis: 
  type-aliases-package: com.cyj.demo.entity # 定义所有操作类的别名所在包
  mapper-locations: classpath*:com/cyj/demo/mapper/*.xml # 所有的mapper映射文件
    
## Logback配置
# spring输出debug级别以上细节  
#logging: 
  #level:     
    #org: 
      #springframework: 
        #web: info
     
  
